# .github/workflows/build.yml

name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'release/**'
    tags:
      - '**'

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive, fetch-depth: 0 }

      # Set a STANDARD JDK for Gradle/AGP
      - name: Set up Temurin 17 (default JDK)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle   # keep Gradle cache

      - uses: gradle/actions/setup-gradle@v4
      - uses: android-actions/setup-android@v3

      - name: Build
        run: |
          ./build.sh --yes

      - name: Pack build/distributions as tar (preserves perms & symlinks)
        run: tar --create --gzip --file=stoic-release.tar.gz --directory=build/distributions .

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: stoic-release-tar-gz
          path: stoic-release.tar.gz
