name: gradle-wrapper

on:
  pull_request:
    paths:
    - 'kotlin/gradlew'
    - 'kotlin/gradlew.bat'
    - 'kotlin/gradle/wrapper/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4
